image: registry.gitlab.com/fdroid/ci-images-server:latest

test:
  script:
    - pip3 install -e .
    - cd tests
    - ./complete-ci-tests

# Test that the parsing of the .txt format didn't change 
# from last released version.
metadata_v0:
  script:
    - cd tests
    - export GITCOMMIT=`git describe`
    - git checkout 0.8  # bump after release
    - cd ..
    - git clone --depth 1 https://gitlab.com/fdroid/fdroiddata
    - cd fdroiddata
    - ../tests/dump_internal_metadata_format.py
    - cd ..
    - git reset --hard
    - git checkout $GITCOMMIT
    - cd fdroiddata
    - ../tests/dump_internal_metadata_format.py
    - diff -uw metadata/dump_*
